augmentation:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Data configuration
data:
  dataset_path: "data/processed"
  image_size: [256, 256]
  num_classes: &num_classes 5
  batch_size: 16
  color_map:
    0: [0, 0, 0]
    1: [222, 31, 7]
    2: [200, 200, 200]
    3: [34, 97, 38]
    4: [0, 69, 255]

# Model configuration
model:
  name: "unet"
  type: "machine_learning"
  params:
    encoder_name: "resnet50"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: *num_classes

# Loss configuration
loss:
  name: "focal"
  params:
    mode: "multiclass"
    alpha: 0.25
    gamma: 2.0

# Optimizer configuration
optimizer:
  name: "adam"
  learning_rate: 0.0001
  params:

# Scheduler configuration
scheduler:
  name: "reduce_on_plateau"
  params:
    mode: "min"
    factor: 0.5
    patience: 5

# Metrics configuration
metrics:
  num_classes: *num_classes
  task: "multiclass"
  average: "macro"

# Training configuration
training:
  epochs: 5
  model_checkpoint: "checkpoints/unet.pth"

# ClearML configuration
clearml:
  project_name: "Aerial Semantic Segmentation"
